# Oxidized with working configuration and sample router.db

FROM oxidized/oxidized:latest
LABEL maintainer="simone.zabberoni@gmail.com"
LABEL description="Oxidized with working configuration and sample router.db"

COPY config /root/.config/oxidized/
COPY router.db /root/.config/oxidized/


