# Keycloak with working realm and client for oxidized
# 0.2

FROM jboss/keycloak
LABEL maintainer="simone.zabberoni@gmail.com"
LABEL description="Keycloak with working realm and client for oxidized"

COPY OxidizedRealm.json /opt/jboss/keycloak/OxidizedRealm.json



