# Keycloak with working realm and client for oxidized

FROM jboss/keycloak
LABEL maintainer="simone.zabberoni@gmail.com"
LABEL description="Keycloak with working realm and client for oxidized"

COPY zabrealm.json /opt/jboss/keycloak/zabrealm.json



